### ISSUE TITLE
Inner and outer off-ramp crash

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#296]
If I have an inner and an outer off-ramp where one has split ratios and the other off-ramp flows I get the following error message:

error.OTMException: This link already has a flowtolinks actuator for this commodity
	at core.Link.register_actuator(Link.java:201)
	at actuator.ActuatorFlowToLinks.initialize(ActuatorFlowToLinks.java:102)
	at control.AbstractController.initialize(AbstractController.java:153)
	at dispatch.EventInitializeController.action(EventInitializeController.java:13)
	at dispatch.Dispatcher.dispatch_events_to_stop(Dispatcher.java:78)
	at core.OTM.advance(OTM.java:180)
	at opt.OTMTask.run_simulation(OTMTask.java:147)
	at opt.OTMTask.call(OTMTask.java:90)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ggomes** [comment]
commit a50424e1e1d654872bacc1c49be84b4638cb96b9 (HEAD -> master)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Wed Feb 10 14:35:14 2021 -0800

    issue 296
