### ISSUE TITLE
Event close ramp

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#297]
I have an off-ramp which has 0 split ratios, so practically it is empty and I have for example on A-B the following plots:
![image](https://user-images.githubusercontent.com/60490284/106645741-9e6aa180-6541-11eb-8635-ab068d98084f.png)
If If add an event to close that off-ramp, I should expect nothing to happen cause that off-ramp was practically not being used at all, it was like closed by default.

However somehow the plots become like this, so there is something going on.
![image](https://user-images.githubusercontent.com/60490284/106645868-ce19a980-6541-11eb-905f-97158b99116d.png)

**Comment by lapardhaja** [comment]
@ggomes for some reason now I receive this error

error.OTMException: This link already has a flowtolinks actuator for this commodity
	at core.Link.register_actuator(Link.java:204)
	at actuator.ActuatorFlowToLinks.initialize(ActuatorFlowToLinks.java:102)
	at control.AbstractController.initialize(AbstractController.java:153)
	at dispatch.EventInitializeController.action(EventInitializeController.java:13)
	at dispatch.Dispatcher.dispatch_events_to_stop(Dispatcher.java:81)
	at core.OTM.advance(OTM.java:193)
	at opt.OTMTask.run_simulation(OTMTask.java:147)
	at opt.OTMTask.call(OTMTask.java:90)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ggomes** [comment]
new OTM
