### ISSUE TITLE
Jam Density exceeded error

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#315]
How is it possible for the jam density to be exceeded?

error.OTMException: error.OTMException: Jam density exceeded
	at core.AbstractLaneGroup.set_lanes(AbstractLaneGroup.java:404)
	at events.EventLanegroupLanes.action(EventLanegroupLanes.java:44)
	at dispatch.Dispatcher.dispatch_events_to_stop(Dispatcher.java:81)
	at core.OTM.advance(OTM.java:193)
	at opt.OTMTask.run_simulation(OTMTask.java:158)
	at opt.OTMTask.call(OTMTask.java:90)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: error.OTMException: Jam density exceeded
	at models.fluid.FluidLaneGroup.set_road_params(FluidLaneGroup.java:108)
	at core.AbstractLaneGroup.set_lanes(AbstractLaneGroup.java:401)
	... 8 more

**Comment by ggomes** [comment]
This has been discussed in a meeting since this issue was opened. It is unavoidable if you decrease the number of lanes.
